language: c

branches:
  only:
  - master

dist: trusty

# The PAL unit tests have a dependency on the PST timezone
env:
  - export TZ=':/usr/share/zoneinfo/America/Los_Angeles'

sudo: required

addons:
  apt:
    packages:
      - pkg-config
      - libpam0g-dev
      - librpm-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - rpm
      - time

before_install:
  - date
  -
  - # /etc/hosts and /etc/resolv.conf not set up with domain as we expect
  - cp /etc/resolv.conf .
  - cat resolv.conf
  - DOMAIN=`grep search resolv.conf | cut -f2 -d\ `
  - echo "domain $DOMAIN" >> resolv.conf
  - cat resolv.conf
  - sudo mv resolv.conf /etc/resolv.conf
  - sudo chown root:root /etc/resolv.conf
  -
  - # Fetch the Build-SCXcore repository for dependencies to build from
  - git config --global 'url.https://github.com/.insteadOf' 'git@github.com:'
  - git clone --recursive 'https://github.com/Microsoft/Build-SCXcore.git' ../bld-scxcore
  -
  - # Master branch for all submodules
  - cd ../bld-scxcore
  - git submodule foreach git checkout master
  -
  - # Patch in the version of SCXcore that Travis gave to us
  - rm -rf opsmgr
  - cp -R ../SCXcore opsmgr

script:
  - cd opsmgr/build
  - ./configure
  - make all test
